module.exports =
    {
        'id': 'row id',
        'sortnumber': 'Sort Number',
        'name': 'Name',
        'category': 'Category',
        'subcategories': 'Subcategories',
        'notesoncategory': 'Notes on Category',
        'doubleexposure': 'Double Exposure',
        'doubleexposuresubcategory': 'Double Exposure Subcategory',
        'doubleexposure2': 'Double Exposure 2',
        'doubleexposuresubcategory2': 'Double Exposure Subcategory 2',
        'doubleexposure3': 'Double Exposure 3',
        'doubleexposuresubcategory3': 'Double Exposure Subcategory 3',
        'pricingcategory': 'Pricing Category',
        'instorespecial': 'In Store Special',
        'storeregularprice': 'Store Reg Price',
        'storespecialprice': 'Store Special Price',
        'mcomspecial': 'MCOM Special',
        'pricinginfo': 'Additional Pricing Info',
        'mcomregprice': 'MCOM Reg Price',
        'mcomspecialprice': 'MCOM Special Price',
        'pricingcomments': 'Pricing Comments',
        'markettointernational': 'Market to International',
        'projectedunits': 'Projected Units',
        'projectedsales': 'MCOM Projected Sales',
        'omniprojectedsales': 'Omni Projected Sales',
        'salesfor2015': 'Sales For 2015',
        'imageid': 'Image Id',
        'arimageid': 'AR Image Id',
        'notesfrombuyersimg': 'Notes on Image from Buyers',
        'notesfromretouchimg':'Notes on Image from Retouching',
        'photoprogress': 'Photo progress',
        'singleormultiple': 'Single or Multiple',
        'featureproductid': 'Feature Product Ids',
        'savedsetid': 'Saved Set Ids',
        'tileimage': 'Tile Image',
        'tilecopy1': 'Tile Copy Line 1',
        'tilecopy2': 'Tile Copy Line 2',
        'tilecopy3': 'Tile Copy Line 3',
        'tilecopy4': 'Tile Copy Line 4',
        'tilestyle': 'Tile Style',
        'plenti': 'Plenti Watermark',
        'bffavorites':'Black Friday Favorites',
        'goingfast': 'Going Fast',
        'alsoinpetites': 'Also in Petites',
        'petitessavedset': 'Petites Saved Set',
        'needsavedset': 'Need Saved Set?',
        'linktype': 'Link Type',
        'livedate': 'Live Date',
        'categoryid': 'Category Id linking',
        'productid': 'Product Id linking',
        'url': 'Url linking',
        'petiteslinktype': 'Petites Link Type',
        'petitescategoryid': 'Petites Category Linking',
        'petitesproductid': 'Petites Product Linking',
        'petitesurl': 'Petites Url Linking',
        'extra': 'Extra',
        'killedrow': 'Killed Row',
        'lockedrow': 'Locked Row',
        'extraomniprojectedsales': 'Extra Omni Projected Sales'
    }
